services:
  - type: web
    name: sonar-rag
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: FAISS_INDEX_DIR
        value: "role1/data/index_minilm"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
